version: '3'

services:
    backend:
        image: ${APP_NAME}:${CURRENT_BRANCH}
        ports:
            - 5000:5000
        environment:
            - POSTGRES_HOST=postgres

    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=default
        volumes: 
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local